// <auto-generated />
using ConsoleApp2.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ConsoleApp2.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ConsoleApp2.Model.Classroom", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Nazev")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Classrooms");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Nazev = "P1"
                        },
                        new
                        {
                            Id = 2L,
                            Nazev = "P2"
                        },
                        new
                        {
                            Id = 3L,
                            Nazev = "P3"
                        },
                        new
                        {
                            Id = 4L,
                            Nazev = "P4"
                        });
                });

            modelBuilder.Entity("ConsoleApp2.Model.Student", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long>("ClassroomId")
                        .HasColumnType("bigint");

                    b.Property<string>("Jmeno")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.Property<string>("Prijmeni")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClassroomId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            ClassroomId = 1L,
                            Jmeno = "A",
                            Prijmeni = "B"
                        },
                        new
                        {
                            Id = 2L,
                            ClassroomId = 1L,
                            Jmeno = "C",
                            Prijmeni = "D"
                        },
                        new
                        {
                            Id = 3L,
                            ClassroomId = 2L,
                            Jmeno = "E",
                            Prijmeni = "F"
                        },
                        new
                        {
                            Id = 4L,
                            ClassroomId = 3L,
                            Jmeno = "G",
                            Prijmeni = "H"
                        });
                });

            modelBuilder.Entity("ConsoleApp2.Model.Student", b =>
                {
                    b.HasOne("ConsoleApp2.Model.Classroom", "Classroom")
                        .WithMany("Students")
                        .HasForeignKey("ClassroomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
